Repository Teal-Insights/r-wbids, pull requests merged in 2024-12, with the labels that each got.

#48 Update counterpart names for Germany
  DESCRIPTION
  R/ids_bulk_files.R
  R/sysdata.rda
  data-raw/wbids-data.R
Labels: enhancement

#53 Update sysdata.rda to new IDS release
  R/sysdata.rda
  data-raw/wbids-data.R
  tests/testthat/test-ids_bulk.R
Labels: enhancement

#55 Fix warning & error in ids bulk download example
  R/ids_bulk.R
  tests/testthat/data/download_bulk_file_output.xlsx
  tests/testthat/data/read_bulk_file_output.rds
  tests/testthat/data/read_bulk_info_output.rds
  tests/testthat/data/sample.rds
  tests/testthat/data/sample.xlsx
  tests/testthat/test-ids_bulk.R
  tests/testthat/test-ids_bulk_files.R
Labels: bug

#57 Changes ids_get() Default Parameters for counterparts and start_date to Reduce Data Volume and Align with User Needs #50
  R/global-variables.R
  R/ids_get.R
  R/sysdata.rda
  data-raw/wbids-data.R
  man/ids_get.Rd
  tests/testthat/test-ids_bulk.R
  tests/testthat/test-ids_get.R
  tests/testthat/test-perform_request.R
Labels: documentation, enhancement
